component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/AppletXMLtoHTML/.*
- ./bin/META-INF/.*
- ./bin/META-INF/services/.*
- ./bin/bin/.*
- ./bin/bin/lib/.*
- ./bin/bin/sql/.*
- ./bin/bin/sql/basic-connection/.*
- ./bin/bin/sql/pquery/.*
- ./bin/bin/sql/show-error/.*
- ./bin/bin/sql/streamable/.*
- ./bin/javax/.*
- ./bin/javax/xml/.*
- ./bin/javax/xml/datatype/.*
- ./bin/javax/xml/namespace/.*
- ./bin/javax/xml/parsers/.*
- ./bin/javax/xml/transform/.*
- ./bin/javax/xml/transform/dom/.*
- ./bin/javax/xml/transform/sax/.*
- ./bin/javax/xml/transform/stream/.*
- ./bin/javax/xml/validation/.*
- ./bin/javax/xml/xpath/.*
- ./bin/lib/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/xalan/.*
- ./bin/org/apache/xalan/client/.*
- ./bin/org/apache/xalan/extensions/.*
- ./bin/org/apache/xalan/lib/.*
- ./bin/org/apache/xalan/lib/sql/.*
- ./bin/org/apache/xalan/processor/.*
- ./bin/org/apache/xalan/res/.*
- ./bin/org/apache/xalan/serialize/.*
- ./bin/org/apache/xalan/templates/.*
- ./bin/org/apache/xalan/trace/.*
- ./bin/org/apache/xalan/transformer/.*
- ./bin/org/apache/xalan/xslt/.*
- ./bin/org/apache/xalan/xsltc/.*
- ./bin/org/apache/xalan/xsltc/cmdline/.*
- ./bin/org/apache/xalan/xsltc/cmdline/getopt/.*
- ./bin/org/apache/xalan/xsltc/compiler/.*
- ./bin/org/apache/xalan/xsltc/compiler/util/.*
- ./bin/org/apache/xalan/xsltc/dom/.*
- ./bin/org/apache/xalan/xsltc/runtime/.*
- ./bin/org/apache/xalan/xsltc/runtime/output/.*
- ./bin/org/apache/xalan/xsltc/trax/.*
- ./bin/org/apache/xalan/xsltc/util/.*
- ./bin/org/apache/xml/.*
- ./bin/org/apache/xml/dtm/.*
- ./bin/org/apache/xml/dtm/ref/.*
- ./bin/org/apache/xml/dtm/ref/dom2dtm/.*
- ./bin/org/apache/xml/dtm/ref/sax2dtm/.*
- ./bin/org/apache/xml/res/.*
- ./bin/org/apache/xml/serializer/.*
- ./bin/org/apache/xml/serializer/dom3/.*
- ./bin/org/apache/xml/serializer/utils/.*
- ./bin/org/apache/xml/utils/.*
- ./bin/org/apache/xml/utils/res/.*
- ./bin/org/apache/xmlcommons/.*
- ./bin/org/apache/xpath/.*
- ./bin/org/apache/xpath/axes/.*
- ./bin/org/apache/xpath/compiler/.*
- ./bin/org/apache/xpath/domapi/.*
- ./bin/org/apache/xpath/functions/.*
- ./bin/org/apache/xpath/jaxp/.*
- ./bin/org/apache/xpath/objects/.*
- ./bin/org/apache/xpath/operations/.*
- ./bin/org/apache/xpath/patterns/.*
- ./bin/org/apache/xpath/res/.*
- ./bin/org/w3c/.*
- ./bin/org/w3c/dom/.*
- ./bin/org/w3c/dom/bootstrap/.*
- ./bin/org/w3c/dom/css/.*
- ./bin/org/w3c/dom/events/.*
- ./bin/org/w3c/dom/html/.*
- ./bin/org/w3c/dom/ls/.*
- ./bin/org/w3c/dom/ranges/.*
- ./bin/org/w3c/dom/stylesheets/.*
- ./bin/org/w3c/dom/traversal/.*
- ./bin/org/w3c/dom/views/.*
- ./bin/org/w3c/dom/xpath/.*
- ./bin/org/xml/.*
- ./bin/org/xml/sax/.*
- ./bin/org/xml/sax/ext/.*
- ./bin/org/xml/sax/helpers/.*
- ./bin/servlet/.*
- ./bin/sql/.*
- ./bin/sql/basic-connection/.*
- ./bin/sql/pquery/.*
- ./bin/sql/show-error/.*
- ./bin/sql/streamable/.*
- ./bin/trax/.*
- ./bin/xml/.*
- ./bin/xml/subdir1/.*
- ./bin/xml/subdir1/subdir2/.*
- ./bin/xsl/.*
- ./bin/xsl/inc1/.*
- ./bin/xsl/inc1/inc2/.*
- ./lib/.*
- ./samples/.*
- ./samples/AppletXMLtoHTML/.*
- ./samples/ApplyXPath/.*
- ./samples/ApplyXPathDOM/.*
- ./samples/CompiledApplet/.*
- ./samples/CompiledBrazil/.*
- ./samples/CompiledEJB/.*
- ./samples/CompiledEJB/lib/.*
- ./samples/CompiledJAXP/.*
- ./samples/CompiledServlet/.*
- ./samples/DOM2DOM/.*
- ./samples/Pipe/.*
- ./samples/SAX2SAX/.*
- ./samples/SimpleTransform/.*
- ./samples/Trace/.*
- ./samples/TransformThread/.*
- ./samples/UseStylesheetPI/.*
- ./samples/UseStylesheetParam/.*
- ./samples/UseXMLFilters/.*
- ./samples/Validate/.*
- ./samples/XPathAPI/.*
- ./samples/bin/.*
- ./samples/bin/AppletXMLtoHTML/.*
- ./samples/bin/bin/.*
- ./samples/bin/bin/lib/.*
- ./samples/bin/bin/sql/.*
- ./samples/bin/bin/sql/basic-connection/.*
- ./samples/bin/bin/sql/pquery/.*
- ./samples/bin/bin/sql/show-error/.*
- ./samples/bin/bin/sql/streamable/.*
- ./samples/bin/lib/.*
- ./samples/bin/servlet/.*
- ./samples/bin/sql/.*
- ./samples/bin/sql/basic-connection/.*
- ./samples/bin/sql/pquery/.*
- ./samples/bin/sql/show-error/.*
- ./samples/bin/sql/streamable/.*
- ./samples/bin/xml/.*
- ./samples/bin/xml/subdir1/.*
- ./samples/bin/xml/subdir1/subdir2/.*
- ./samples/bin/xsl/.*
- ./samples/bin/xsl/inc1/.*
- ./samples/bin/xsl/inc1/inc2/.*
- ./samples/extensions/.*
- ./samples/extensions/bin/.*
- ./samples/extensions/bin/lib/.*
- ./samples/extensions/bin/sql/.*
- ./samples/extensions/bin/sql/basic-connection/.*
- ./samples/extensions/bin/sql/pquery/.*
- ./samples/extensions/bin/sql/show-error/.*
- ./samples/extensions/bin/sql/streamable/.*
- ./samples/extensions/lib/.*
- ./samples/extensions/sql/.*
- ./samples/extensions/sql/basic-connection/.*
- ./samples/extensions/sql/ext-connection/.*
- ./samples/extensions/sql/pquery/.*
- ./samples/extensions/sql/show-error/.*
- ./samples/extensions/sql/streamable/.*
- ./samples/lib/.*
- ./samples/servlet/.*
- ./samples/translets/.*
- ./samples/trax/.*
- ./samples/trax/xml/.*
- ./samples/trax/xml/subdir1/.*
- ./samples/trax/xml/subdir1/subdir2/.*
- ./samples/trax/xsl/.*
- ./samples/trax/xsl/inc1/.*
- ./samples/trax/xsl/inc1/inc2/.*
- ./tools/.*
- ./xdocs/.*
- ./xdocs/style/.*
- ./xdocs/style/dtd/.*
- ./xdocs/style/graphics/.*
- ./xdocs/style/stylesheets/.*
